seo: 
  site_name: Fresh 'n Wild
  title: Fresh 'n Wild | Outdoor Dining, Catering & Events in Windhoek, Namibia
  description: 
  keywords: 
  social_image: 
  author: 
  favicon_image: 
social: 
  instagram_username:
  facebook_url: